### ISSUE TITLE
How to scrape all the data in a page with infinite scrolling

### ISSUE THREAD

**Issue by CathyChang1996** [hupili/python-for-data-and-media-communication-gitbook#127] opened 2018-12-03 05:37 UTC
# Troubleshooting

## Describe your environment

* Operating system:OS
* Python version:3.7
* Hardware:Macbook
* Internet access:
* Jupyter notebook or not? [Y/N]:Y
* Which chapter of book?: W6

## Describe your question

When I tried to scrape all the location names in a page, I found it should be with a infinite scrolling process to get all the information, how to make it happen?

## The minimum code (snippet) to reproduce the issue

```url = ['http://www.mafengwo.cn/u/69932798/review.html']


filtered=[]
for u in url:
    filter=u[:-5]
    filtered.append(filter)
    
import time
from selenium import webdriver
review_url=[]
for urls in filtered:
    review= '{}/review.html'.format(urls)
    review_url.append(review)

browser = webdriver.Chrome()
data=[]
for i in review_url:
    browser.get(i)
    time.sleep(2)
    try:
        number= browser.find_elements_by_tag_name('b')[2].text
        place= browser.find_elements_by_css_selector('h3.title')
        place_of_interests=[]
        for p in place:
            aab=p.text
            place_of_interests.append(aab)
        cleaned_place=[]
        for x in place_of_interests:
            clean=x.replace('\n', '/')
            cleaned_place.append(clean)
        data.append([i,number,cleaned_place])
        browser.execute_script('window.scrollTo(0, document.body.scrollHeight);')
    except:
        print(Error_Raise)
```

**Comment by CathyChang1996** [comment] 2018-12-03 05:38
url = ['http://www.mafengwo.cn/u/69932798/review.html']

**Comment by CathyChang1996** [comment] 2018-12-03 08:48
Problem solved! Thanks a lot!

**Comment by hupili** [comment] 2018-12-03 15:05
Although the problem is solved, I leave an alternative solution here: https://github.com/hupili/python-for-data-and-media-communication/blob/master/scraper-examples/mafengwo-xhr.ipynb  

Crawling by network trace analysis and XHR is also common. However, the analysis is case by case so we only [briefly mentioned in the notes](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-06.md#analyse-network-traces)

**Comment by ChicoXYC** [comment] 2018-12-18 11:52
Closed. Merged this issue into FAQs, please refer [here](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/module-selenium.md#infinite-scroll-in-a-single-page).

**Closed** 2018-12-18 11:52 UTC
