### ISSUE TITLE
nbviewer.jupyter.org cannot read interactive charts of my ipynb file

### ISSUE THREAD

**Issue by DidoChan** [hupili/python-for-data-and-media-communication-gitbook#102] opened 2018-11-23 14:00 UTC
# Troubleshooting

## Describe your environment

* Operating system:
* Python version:
* Hardware:
* Internet access:
* Jupyter notebook or not? [Y/N]:Y
* Which chapter of book?:

## Describe your question
Nbviewer.jupyter.org cannot read all interactive charts of my ipynb file which can run successfully on the jupyter environment.

Image1:It runs successfully on the jupyter environment----
![wechatimg835](https://user-images.githubusercontent.com/42913830/48947044-c37b2700-ef6a-11e8-9ec4-2305273e0509.jpeg)

Image2:Ooops on the Nbviewer.jupyter.org----
![wechatimg834](https://user-images.githubusercontent.com/42913830/48947135-1ce35600-ef6b-11e8-9f46-1f4c28ec41f9.jpeg)

**Comment by hupili** [comment] 2018-11-23 14:22
Seems duplicate of #93 . Can you try this? https://github.com/hupili/python-for-data-and-media-communication-gitbook/issues/93#issuecomment-440897753

**Comment by DidoChan** [comment] 2018-11-24 10:03
> Seems duplicate of #93 . Can you try this? [#93 (comment)](https://github.com/hupili/python-for-data-and-media-communication-gitbook/issues/93#issuecomment-440897753)

It works !

**Comment by DidoChan** [comment] 2018-11-24 10:18
> Seems duplicate of #93 . Can you try this? [#93 (comment)](https://github.com/hupili/python-for-data-and-media-communication-gitbook/issues/93#issuecomment-440897753)

However the other static charts cannt show which appeared successfully yesterday......
image1:static charts coding works on jypyter environment.
![222](https://user-images.githubusercontent.com/42913830/48966972-ee21ba00-f014-11e8-87ed-76ee42354428.jpeg)

image2:static charts cannot show on nbviewer.jupyter.org.
![1111](https://user-images.githubusercontent.com/42913830/48966973-f4b03180-f014-11e8-8c06-3f3fc43fd93d.jpeg)

**Comment by ChicoXYC** [comment] 2018-11-25 11:57
Merged those two issues in notes, please refer [here](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/module-jupyter.md#display-charts-in-nbviwer).

**Closed** 2018-11-25 12:19 UTC
